### PR TITLE
Adding support for emojis and foreign languages

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @alexellis 

as discussed, the PR for your consideration. It's largely based on https://developers.google.com/web/tools/puppeteer/troubleshooting#running_puppeteer_in_docker

Cheers,
Peter

### CODE REVIEW

**Comment by alexellis** [comment]
What's the difference in Docker image size before/after?

**Comment by spekulatius** [comment]
According to docker hubs information it changes from:

image

to

image

Quite a jump, not sure if I can get it smaller. Might be okay. After all , it's installing fonts for the rest of the world. Any ideas on how to reduce the size?

**Comment by alexellis** [comment]
Please can you use the additional packages method instead?

Simply run the commands that don't fit into the pattern in the single base Dockerfile and let's retain only one template to avoid so much repetition.

**Comment by alexellis** [comment]
I've gone ahead and made the changes myself, please see 5045f6d which you are welcome to continue using under the terms of the license.

**Comment by spekulatius** [comment]
Thanks for taking care of this - I had it on my todo list after the launch. Slowly catching up... 

No worries, the license is and was always considered.

**Pull request closed without merging**
